apiVersion: v1
kind: Service
metadata:
  name: simple-spring
spec:
  type: ClusterIP
  selector:
    app: simple-spring
  ports:
  - protocol: TCP
    # Expose port 8080 on the Service so you can port-forward 8080:8080
    port: 8080
    targetPort: 8080

